### ISSUE TITLE
xphoop

### ISSUE THREAD

**Issue by yuesheng1234** [ReaJason/17wanxiaoCheckin#102]
在lsp模块里面看见deviced变成00000000-7813-9。。。。。。这种怎么填到代码里面

**Comment by ReaJason** [comment]
就是配置文件的 deviceID 这个值

**Comment by yuesheng1234** [comment]
以前的是一串数字，不知道因为安卓版本问题还是什么变成数字加-了

**Comment by ReaJason** [comment]
> 以前的是一串数字，不知道因为安卓版本问题还是什么变成数字加-了

完美校园 app 升级之后变成的这个样子

**Comment by yuesheng1234** [comment]
我的完美校园还是5.3.6的，所以带-的id也能用吗，发现手机的imei码可以充当deviceid使用

**Comment by ReaJason** [comment]
可以用，试一试，我的就是带 - 的，只有低版本的安卓机才能 imei 当 deviceid 使
