### ISSUE TITLE
每次重新登录完美校园就要重新注册设备

### ISSUE THREAD

**Issue by Yortl** [ReaJason/17wanxiaoCheckin#65]
能解决设备ID的问题就好了

**Comment by ReaJason** [comment]
> 能解决设备ID的问题就好了

目前没找到好的办法，建议使用支付宝小程序的完美校园，或者注册一个新号用来登录获取token，配置文件的打卡数据全部填写成自己的数据，由于完美校园并不会检查token和用户信息的比对，所以可以使用别的账号来为你提交自己的打卡信息

**Comment by ReaJason** [comment]
> 能解决设备ID的问题就好了

目前已发现 xp hook 的方法获取本机 deviceId，没有测试虚拟框架是否可行，magisk+lsposed 已测试可以
