### ISSUE TITLE
为什么返回值{'code': 0, 'msg': '成功'}，在支付宝健康助手也显示打卡正常，但是后台就显示我没有打卡，有没有大佬给我解答一下，谢谢

### ISSUE THREAD

**Issue by yedaoyu** [ReaJason/17wanxiaoCheckin#66]
为什么返回值{'code': 0, 'msg': '成功'}，在支付宝健康助手也显示打卡正常，但是后台就显示我没有打卡，有没有大佬给我解答一下，谢谢

**Comment by ReaJason** [comment]
1. 可能你选错方式了，这是第二类健康打卡的成功结果
2. 如果你是第二类健康打卡，你可能经纬度配置文件没有填写好
3. 其他原因
