### ISSUE TITLE
打卡失败，控制台提示以下信息

### ISSUE THREAD

**Issue by Oiaslly** [ReaJason/17wanxiaoCheckin#73]
![QQ截图20220104215220](https://user-images.githubusercontent.com/97106988/148069601-f21911c8-e9ea-477d-bdec-d9c0abd6f773.jpg)
之前都是正常的

**Comment by ReaJason** [comment]
看着像是 from Crypto.Cipher import DES3 导包时，包内部的错误，错误重试应该就没事了

**Comment by Oiaslly** [comment]
重新获取设备ID和用新的scf包重新上传都试过了，还是不行，求解答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 上午9:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ReaJason/17wanxiaoCheckin] 打卡失败，控制台提示以下信息 (Issue #73)





 
看着像是 from Crypto.Cipher import DES3 导包时，包内部的错误，错误重试应该就没事了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ReaJason** [comment]
> > 看着像是 from Crypto.Cipher import DES3 导包时，包内部的错误，错误重试应该就没事了
> 
> 重新获取设备ID和用新的scf包重新上传都试过了，还是不行，求解

你如果还是报这个错误的话，尝试打开 src/Crypto/Cipher/__init__.py 看第 36 行，Cipher 有没有多余的空格删掉

**Comment by Oiaslly** [comment]
> 

确实多了个空格，解决了，感谢！
