### ISSUE TITLE
本地测试成功，上传到腾讯云函数就不行了，安装绑定过层的

### ISSUE THREAD

**Issue by zmcccc** [ReaJason/17wanxiaoCheckin#74]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 169, in main_handler\n    user_config_dict = load_config(kwargs['user_config_path'])\nKeyError: 'user_config_path'","statusCode":430}

**Comment by ReaJason** [comment]
云函数就用云函数的那个压缩包，云函数入口需要做一点修改的
