### ISSUE TITLE
第二类健康打卡

### ISSUE THREAD

**Issue by Lhh928** [ReaJason/17wanxiaoCheckin#80]
新的模板有吗

**Comment by ReaJason** [comment]
> 

现在第二类打卡是有问题了吗，没账号不知道

**Comment by Lhh928** [comment]
没事了，是我们打卡换成第一类打卡了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月22日(星期六) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin] 第二类健康打卡 (Issue #80)





   
现在第二类打卡是有问题了吗，没账号不知道
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
