### ISSUE TITLE
现在无法获取device id

### ISSUE THREAD

**Issue by LongMarch3174** [ReaJason/17wanxiaoCheckin#84]
提供的软件显示交换密钥失败
而我抓包后，在请求体里面该如何获得device id？

**Comment by MoYuToGo** [comment]
抓包url：http://server.17wanxiao.com/YKT_Interface/xyk 
打开完美校园，全部应用->校园卡
当请求体中method=WX_BASE_INFO时，会有device id

**Comment by LongMarch3174** [comment]
device id是一串什么样的字符，可以在抓包到的信息中获取吗？
还是得通过xp hook获取

**Comment by LongMarch3174** [comment]
我抓包后已经看到了请求体中有“method=WX_BASE_INFO”
![image](https://user-images.githubusercontent.com/97907269/163406974-8026cfe0-4ca5-41e9-8a35-9f94f4839c8c.png)

**Comment by MoYuToGo** [comment]
在响应体中
JSON -> deviceId
格式与token一致，
类似于11342899-d288-ee92-65e9-65e9ad5bbbff

**Comment by LongMarch3174** [comment]
好的，在您的帮助下我已经完成了对device id的获取，并成功完成了函数的填写与自动化，感谢🙏🏻。
