### ISSUE TITLE
测试失败,如何解决?

### ISSUE THREAD

**Issue by ChinaZhangYibo** [ReaJason/17wanxiaoCheckin#87]
START RequestId: 69dc737c-b0b1-4560-b8b4-c43496837b15

Init Report RequestId: 69dc737c-b0b1-4560-b8b4-c43496837b15 Coldstart: 361ms (PullCode: 228ms InitRuntime: 9ms InitFunction: 124ms) Memory: 128MB MemUsage: 7.91MB

ERROR RequestId: 69dc737c-b0b1-4560-b8b4-c43496837b15 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python37/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python37/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python37/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python37/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/user/index.py", line 4, in <module>     from api.campus_check import get_id_list_v1, get_id_list_v2, get_customer_type_id, get_campus_check_post, \   File "/var/user/api/campus_check.py", line 13, in <module>     import requests ModuleNotFoundError: No module named 'requests'", "statusCode": 443}

END RequestId: 69dc737c-b0b1-4560-b8b4-c43496837b15

Report RequestId: 69dc737c-b0b1-4560-b8b4-c43496837b15 Duration: 0ms Memory: 128MB MemUsage: 7.91MB

START RequestId:69dc737c-b0b1-4560-b8b4-c43496837b15

ERROR RequestId:69dc737c-b0b1-4560-b8b4-c43496837b15 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 696, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 677, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 728, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 4, in \u003cmodule\u003e\n    from api.campus_check import get_id_list_v1, get_id_list_v2, get_customer_type_id, get_campus_check_post, \\\n  File \"/var/user/api/campus_check.py\", line 13, in \u003cmodule\u003e\n    import requests\nModuleNotFoundError: No module named 'requests'","statusCode":443}

END RequestId:69dc737c-b0b1-4560-b8b4-c43496837b15

Report RequestId:69dc737c-b0b1-4560-b8b4-c43496837b15 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by ReaJason** [comment]
请使用 python3.6 的运行环境，我打包的 scf 压缩包只有 3.6 版本的
