### ISSUE TITLE
未在根目录下找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

### ISSUE THREAD

**Issue by diyumalatang** [ReaJason/17wanxiaoCheckin#92]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79008681/177340114-f0d86191-a5d7-4df0-8f02-7a3b4444205e.png">

**Comment by By-The** [comment]
你上传的是压缩包吧，把压缩包解压一下，修改user.json以后重新上传文件夹
