### ISSUE TITLE
测试失败

### ISSUE THREAD

**Issue by ALEX-mercer-help** [ReaJason/17wanxiaoCheckin#93]
我按照https://blog.csdn.net/m0_51607907/article/details/125606549?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166044185716780366544815%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166044185716780366544815&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-125606549-null-null.142^v40^control,185^v2^control&utm_term=%E5%AE%8C%E7%BE%8E%E6%A0%A1%E5%9B%AD%E8%87%AA%E5%8A%A8%E6%89%93%E5%8D%A1&spm=1018.2226.3001.4187 这个连接的步骤来的，最后一步测试失败了，求告知解决办法

执行日志
START RequestId: 50b36cb1-7e60-4acb-aa57-10973f0bfe2d

Init Report RequestId: 50b36cb1-7e60-4acb-aa57-10973f0bfe2d Coldstart: 586ms (PullCode: 0ms InitRuntime: 4ms InitFunction: 582ms) Memory: 64MB MemUsage: 17.46MB

ERROR RequestId: 50b36cb1-7e60-4acb-aa57-10973f0bfe2d Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 13, in <module>     from login import CampusLogin   File "/var/user/login/__init__.py", line 14, in <module>     from login.campus import CampusLogin   File "/var/user/login/campus.py", line 19, in <module>     from login import des_3   File "/var/user/login/des_3.py", line 1, in <module>     from Crypto.Cipher import DES3 ModuleNotFoundError: No module named 'Crypto'", "statusCode": 443}

END RequestId: 50b36cb1-7e60-4acb-aa57-10973f0bfe2d

Report RequestId: 50b36cb1-7e60-4acb-aa57-10973f0bfe2d Duration: 0ms Memory: 64MB MemUsage: 17.46MB

START RequestId:50b36cb1-7e60-4acb-aa57-10973f0bfe2d

ERROR RequestId:50b36cb1-7e60-4acb-aa57-10973f0bfe2d Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 13, in \u003cmodule\u003e\n    from login import CampusLogin\n  File \"/var/user/login/__init__.py\", line 14, in \u003cmodule\u003e\n    from login.campus import CampusLogin\n  File \"/var/user/login/campus.py\", line 19, in \u003cmodule\u003e\n    from login import des_3\n  File \"/var/user/login/des_3.py\", line 1, in \u003cmodule\u003e\n    from Crypto.Cipher import DES3\nModuleNotFoundError: No module named 'Crypto'","statusCode":443}

END RequestId:50b36cb1-7e60-4acb-aa57-10973f0bfe2d

Report RequestId:50b36cb1-7e60-4acb-aa57-10973f0bfe2d Duration:0ms Memory:64MB MemUsage:0.000000MB

**Comment by ALEX-mercer-help** [comment]
不知道哪里出错了

**Comment by By-The** [comment]
CSDN上面的搬运工都跑路了，部署项目前仔细阅读本项目的REDME.md
