### ISSUE TITLE
获取token失败

### ISSUE THREAD

**Issue by 2211649442** [ReaJason/17wanxiaoCheckin#94]
总是会获取token失败，有时候又可以打卡成功

**Comment by 2211649442** [comment]
有时候获取token失败 有时候又可以成功打卡

**Comment by cjw414522569** [comment]
我也是

**Comment by 2211649442** [comment]
可有解决办法吗发自我的 iPhone在 2022年9月12日，20:45，cjw414522569 ***@***.***> 写道：﻿
我也是

**Comment by cjw414522569** [comment]
我试了好多办法，改密码。换家庭ip，还是不行，但是我3个舍友的号完全没有出现这个问题，只有我的出现了，可能是被完美校园管理员搞了

**Comment by 2211649442** [comment]
我现在改成了每天打卡10次 总有几次会获取token失败 一般 不会全失败 有成果的就行在 2022年9月12日，22:51，cjw414522569 ***@***.***> 写道：﻿
我试了好多办法，改密码。换家庭ip，还是不行，但是我3个舍友的号完全没有出现这个问题，只有我的出现了，可能是被完美校园管理员搞了

**Comment by 806013096** [comment]
已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。

**Comment by 2211649442** [comment]
但是我是用ios 的抓包抓的发自我的 iPhone在 2022年9月15日，17:43，QQ邮箱 ***@***.***> 写道：﻿我现在用的就是我自己抓包的设备Id 还是会获取token失败发自我的 iPhone在 2022年9月15日，17:08，cc199901011 ***@***.***> 写道：﻿
已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。

**Comment by 806013096** [comment]
那这个就真的是完美那边的问题了，就是这个月初出现的问题，我现在用着还没问题，就是不知道过段时间会不会出问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ReaJason/17wanxiaoCheckin] 获取token失败 (Issue #94)





 但是我是用ios 的抓包抓的发自我的 iPhone在 2022年9月15日，17:43，QQ邮箱 ***@***.***&gt; 写道：﻿我现在用的就是我自己抓包的设备Id 还是会获取token失败发自我的 iPhone在 2022年9月15日，17:08，cc199901011 ***@***.***&gt; 写道：﻿
 已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。

**Comment by cjw414522569** [comment]
我才刚刚安卓抓好包你们就告诉我这个噩耗

**Comment by 2211649442** [comment]
😂在 2022年9月15日，17:50，cjw414522569 ***@***.***> 写道：﻿
我才刚刚安卓抓好包你们就告诉我这个噩耗

**Comment by 806013096** [comment]
> 我才刚刚安卓抓好包你们就告诉我这个噩耗

最新消息，token失败无解嗷，最佳办法多打几次卡，刚刚测试一样没用

**Comment by 806013096** [comment]
> 😂在 2022年9月15日，17:50，cjw414522569 ***@***.***> 写道：﻿ 我才刚刚安卓抓好包你们就告诉我这个噩耗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

我直接1分钟打5次最后成功了，函数还是抓包id

**Comment by yzy26353520** [comment]
> 已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。

你好，请问可以细说吗

**Comment by 806013096** [comment]
https://reajason.top/2021/04/18/17wanxiaohookgetdeviceid/，用这个网站里面给的xp框架软件抓包，不过也就稳定一点，最好的方法就是多打几次卡，5分钟打10次总有一次成功的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin] 获取token失败 (Issue #94)





  
已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。
  
你好，请问可以细说吗

**Comment by LongMarch3174** [comment]
现在已经趋于稳定，我定的1点，5点，6点，7点30分的自动打卡已均能打卡。约两个星期前七点半的始终无法成功，其余都可，九月初定的0点30分和8点均不能成功

**Comment by cjw414522569** [comment]
最新反馈，凌晨一点打卡不会获取token失败，0-7点没有任何问题，白天很大几率打不了卡

**Comment by 806013096** [comment]
确实现在稳定很多了，当时就是完美那边服务器有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月3日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin] 获取token失败 (Issue #94)





 
现在已经趋于稳定，我定的1点，5点，6点，7点30分的自动打卡已均能打卡。约两个星期前七点半的始终无法成功，其余都可，九月初定的0点30分和8点均不能成功

**Comment by 806013096** [comment]
那就是完美那边服务器有问题白天打卡人太多了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 凌晨1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin] 获取token失败 (Issue #94)





 
最新反馈，凌晨一点打卡不会获取token失败，0-7点没有任何问题，白天很大几率打不了卡

**Comment by 2211649442** [comment]
我现在用的就是我自己抓包的设备Id 还是会获取token失败发自我的 iPhone在 2022年9月15日，17:08，cc199901011 ***@***.***> 写道：﻿
已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。

**Comment by cjw414522569** [comment]
电脑版的exe文件获取的device_id可以用，定时打卡调在1-7点之间就行了

**Comment by 2211649442** [comment]
行吧 谢谢啦发自我的 iPhone在 2022年9月15日，17:47，cc199901011 ***@***.***> 写道：﻿
那这个就真的是完美那边的问题了，就是这个月初出现的问题，我现在用着还没问题，就是不知道过段时间会不会出问题









------------------&nbsp;原始邮件&nbsp;------------------

发件人: ***@***.***&gt;; 

发送时间: 2022年9月15日(星期四) 下午5:45

收件人: ***@***.***&gt;; 

抄送: ***@***.***&gt;; ***@***.***&gt;; 

主题: Re: [ReaJason/17wanxiaoCheckin] 获取token失败 (Issue #94)











 但是我是用ios 的抓包抓的发自我的 iPhone在 2022年9月15日，17:43，QQ邮箱 ***@***.***&gt; 写道：﻿我现在用的就是我自己抓包的设备Id 还是会获取token失败发自我的 iPhone在 2022年9月15日，17:08，cc199901011 ***@***.***&gt; 写道：﻿

 已解决，电脑版的那个exe文件获取的device_id用不了了，应该是完美那边服务器更新策略了。解决方案就是用主页的另一个方法[xp hook]抓包app端的id，手机下载VMOS这个软件自带xp框架，抓包出来的id填上去就可以了，抓出来的数据很长是对的直接填就可以了。

**Comment by ReaJason** [comment]
请尝试获取最新的代码，最新的代码添加了交换密钥失败的重试机制

**Comment by 806013096** [comment]
好的，谢谢老哥了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin] 获取token失败 (Issue #94)





 
请尝试获取最新的代码，最新的代码添加了交换密钥失败的重试机制
