### ISSUE TITLE
 [Errno 完美校园交换密钥失败] ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

### ISSUE THREAD

**Issue by yzy26353520** [ReaJason/17wanxiaoCheckin#98]
## 环境：
家用电脑i5-12600k，windows10，Python 3.7.8
在计划任务里添加了“打卡10点”的任务，配置如下：
![image](https://user-images.githubusercontent.com/83323222/191151861-b6dd85f2-9384-417e-8b74-132195895a32.png)
![image](https://user-images.githubusercontent.com/83323222/191151914-6ed072bd-8a0b-458c-8159-f842b1aa4ebf.png)

## 遇到的问题：
在10点能准时弹出cmd框框，但出错（无论勾选使用最高权限都出错）：

> 2022-09-20 10:00:02 - [INFO] - 用户一，xxx
> 2022-09-20 10:00:03 - [WARNING] - [Errno 完美校园交换密钥失败] ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> 2022-09-20 10:00:03 - [WARNING] - 1771，获取token失败，打卡失败，

而我在计划任务里手动运行该任务，则成功：
![image](https://user-images.githubusercontent.com/83323222/191152165-c1ebcd57-506c-4d98-930c-8ce8017c68aa.png)

> 2022-09-20 10:13:41 - [INFO] - 用户一，xxx
> 2022-09-20 10:13:43 - [INFO] - 1771，登录成功
> 2022-09-20 10:13:44 - [INFO] - 刘-湖南工业大学，获取个人信息成功
> 2022-09-20 10:13:45 - [INFO] - 完美校园第一类健康打卡post参数获取成功

## 求解
如何解决`远程主机强迫关闭了一个现有的连接`的问题

**Comment by yzy26353520** [comment]
在注册表里开机启动，也会遇到同样的问题。
注册表在

> 计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run\新值 #1

设置值为
`cmd /k python D:\Users\David\Documents\17wanxiaoCheckin-master\index.py`
![image](https://user-images.githubusercontent.com/83323222/191408974-f26d333d-be03-4e18-82b9-cf286a1d57f4.png)

**Comment by yzy26353520** [comment]
用[这个解决方法](https://www.cnblogs.com/widows/p/13328291.html)，失败
然后尝试了[这个方法](https://blog.csdn.net/andyguan01_2/article/details/86488311)，注册表开机启动项，运行成功，未出错

**Comment by yzy26353520** [comment]
> 用[这个解决方法](https://www.cnblogs.com/widows/p/13328291.html)，失败 然后尝试了[这个方法](https://blog.csdn.net/andyguan01_2/article/details/86488311)，注册表开机启动项，运行成功，未出错

这个方法又行不通了。但是又发现了新的现象：
![image](https://user-images.githubusercontent.com/83323222/192402534-1401e41e-4a84-4eb7-b2e3-b27bc3b64968.png)
第一个用户不能打卡，但第二个用户能打卡

**Comment by bylengfeng** [comment]
设置重复打卡就行

**Comment by ReaJason** [comment]
交换密钥失败的问题，最新的代码添加了重试，应该能解决
